/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bip;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author jesus
 */
public class bus extends javax.swing.JInternalFrame {

    /**
     * Creates new form student
     */
    Connection con;
    DBConnect dbc= new DBConnect();
    public bus() {
        initComponents();
                initComponents();
         try {
            con=dbc.Connect();
        } catch (SQLException ex) {
            Object e = null;
            JOptionPane.showMessageDialog(null,e);
        }
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        capacity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        busid1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        busno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        availyes = new javax.swing.JRadioButton();
        availno = new javax.swing.JRadioButton();
        add_bus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        busid2 = new javax.swing.JTextField();
        update_student = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        busid3 = new javax.swing.JTextField();
        remove_bus = new javax.swing.JButton();
        addbuserror = new javax.swing.JLabel();
        removebuserror = new javax.swing.JLabel();
        updatebuserror = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 0));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD BUS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel1)
                .addContainerGap(512, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("BUS ID:");

        capacity.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("CAPACITY:");

        busid1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("NO. PLATE NUMBER:");

        busno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        busno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busnoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("AVAILABILITY:");

        buttonGroup1.add(availyes);
        availyes.setForeground(new java.awt.Color(51, 51, 51));
        availyes.setText("YES");
        availyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availyesActionPerformed(evt);
            }
        });

        buttonGroup1.add(availno);
        availno.setForeground(new java.awt.Color(51, 51, 51));
        availno.setText("NO");
        availno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availnoActionPerformed(evt);
            }
        });

        add_bus.setBackground(new java.awt.Color(102, 153, 255));
        add_bus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_bus.setForeground(new java.awt.Color(255, 255, 255));
        add_bus.setText("ADD");
        add_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_busActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UPDATE AVAILABILITY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("BUS ID:");

        busid2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        update_student.setBackground(new java.awt.Color(102, 153, 255));
        update_student.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update_student.setForeground(new java.awt.Color(255, 255, 255));
        update_student.setText("UPDATE");
        update_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_studentActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REMOVE BUS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("BUS ID:");

        busid3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        remove_bus.setBackground(new java.awt.Color(102, 153, 255));
        remove_bus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        remove_bus.setForeground(new java.awt.Color(255, 255, 255));
        remove_bus.setText("REMOVE");
        remove_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_busActionPerformed(evt);
            }
        });

        addbuserror.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addbuserror.setForeground(new java.awt.Color(255, 0, 0));

        removebuserror.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removebuserror.setForeground(new java.awt.Color(255, 0, 0));

        updatebuserror.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updatebuserror.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(add_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addbuserror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(busid2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(availyes)
                                .addGap(18, 18, 18)
                                .addComponent(availno))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(busid1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(busno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(capacity, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(remove_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(busid3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(removebuserror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(update_student, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updatebuserror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busid1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbuserror, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busid2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availyes)
                    .addComponent(availno))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_student, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebuserror, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busid3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remove_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removebuserror, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void availyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availyesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availyesActionPerformed
    int status;
    public int capacityvalid(int no) {
    if (no <= 30&& no >= 80) {
        return 1;
    } else {
        return 0;
    }
    }
    private void availnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availnoActionPerformed

    private void add_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_busActionPerformed
    String sql = "INSERT INTO Bus (bus_id,bus_number,capacity,availability) VALUES (?, ?, ?, ?)";
    // Create a PreparedStatement and initialize it outside of try-catch.
    PreparedStatement pstmt = null;
    
    try {
        // Prepare the PreparedStatement with the SQL query.
        pstmt = con.prepareStatement(sql);

        // Set the values for the placeholders in the SQL query.
        pstmt.setInt(1, Integer.parseInt(busid1.getText()));
        pstmt.setString(2,busno.getText());
        String capacityText = capacity.getText();
        int capacityValue;
        try {
            capacityValue = Integer.parseInt(capacityText);
        } catch (NumberFormatException ex) {
            // Handle the case where the text is not a valid integer.
            JOptionPane.showMessageDialog(null, "Please enter a valid capacity (numeric value).");
            return; // Exit the method.
        }
        pstmt.setInt(3,capacityValue);
        pstmt.setInt(4,1);
        int rowsInserted = pstmt.executeUpdate();
        if (rowsInserted > 0) {
            // If the insertion is successful, show a success message.
            addbuserror.setText("Successfully Added!!");
        } else {
            // If no rows were inserted, show an error message.
            addbuserror.setText("Failed to add the Bus.");
        }
    } catch (SQLException ex) {
        // Handle any database-related errors.
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    } finally {
        // Close the PreparedStatement in the finally block to ensure it is always closed.
        if (pstmt != null) {
            try {
                pstmt.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    }//GEN-LAST:event_add_busActionPerformed

    private void update_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_studentActionPerformed
        // TODO add your handling code here:
            String workerIdText = busid2.getText();
    int admin;
    if (!workerIdText.isEmpty()) {
    try {
        admin = Integer.parseInt(workerIdText);
    } catch (NumberFormatException ex) {
        // Handle the case where the text is not a valid integer.
        JOptionPane.showMessageDialog(null, "Please enter a valid worker ID (numeric value).");
        return; // Exit the method.
    }
    } else {
    // Handle the case where the field is empty.
    JOptionPane.showMessageDialog(null, "Please enter a worker ID.");
    return; // Exit the method.
    }
    int avail;
    if (availyes.isSelected()) {
        avail = 1;
    } else if (availno.isSelected()) {
        avail = 0;
    } else {
        // Handle the case where neither option is selected.
        return; // You may want to show an error message here.
    }

    try {
        // Define the SQL query to update the student's availability.
        String sql = "UPDATE BUS SET Availability = ? WHERE Bus_id = ?";

        // Create a PreparedStatement and set the parameters.
        PreparedStatement pstmt = con.prepareStatement(sql);
        pstmt.setInt(1, avail);
        pstmt.setInt(2, admin);

        // Execute the SQL query to update the student's availability.
        int rowsUpdated = pstmt.executeUpdate();

        if (rowsUpdated > 0) {
            // If the update is successful, show a success message.
            updatebuserror.setText("Successfully Updated!!");
        } else {
            // If no rows were updated, show an error message.
            updatebuserror.setText("No Bus found with BusId: " + admin);
        }

        pstmt.close(); // Close the PreparedStatement.

    } catch (SQLException ex) {
        // Handle any database-related errors.
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_update_studentActionPerformed

    private void remove_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_busActionPerformed
        // TODO add your handling code here:
            int admin = Integer.parseInt(busid3.getText());
    try {
        // Define the SQL query to update the student's availability.
        String sql = "DELETE FROM BUS WHERE BUS_ID = ?";

        // Create a PreparedStatement and set the parameters.
        PreparedStatement pstmt = con.prepareStatement(sql);
        pstmt.setInt(1, admin);

        // Execute the SQL query to update the student's availability.
        int rowsUpdated = pstmt.executeUpdate();

        if (rowsUpdated > 0) {
            // If the update is successful, show a success message.
            removebuserror.setText("Successfully Removed!!");
        } else {
            // If no rows were updated, show an error message.
            removebuserror.setText("No Bus found with Bus ID: " + admin);
        }

        pstmt.close(); // Close the PreparedStatement.

    } catch (SQLException ex) {
        // Handle any database-related errors.
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_remove_busActionPerformed

    private void busnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_bus;
    private javax.swing.JLabel addbuserror;
    private javax.swing.JRadioButton availno;
    private javax.swing.JRadioButton availyes;
    private javax.swing.JTextField busid1;
    private javax.swing.JTextField busid2;
    private javax.swing.JTextField busid3;
    private javax.swing.JTextField busno;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField capacity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton remove_bus;
    private javax.swing.JLabel removebuserror;
    private javax.swing.JButton update_student;
    private javax.swing.JLabel updatebuserror;
    // End of variables declaration//GEN-END:variables
}
