/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bip;

import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jesus
 */
public class viewbus extends javax.swing.JInternalFrame {

    /**
     * Creates new form student
     */
    Connection con;
    DBConnect dbc= new DBConnect();
    public viewbus() {
        initComponents();
        try {
        con=dbc.Connect();
        } catch (SQLException ex) {
            Logger.getLogger(LOGIN.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        availyes = new javax.swing.JRadioButton();
        availno = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BusTable = new javax.swing.JTable();
        show_bus = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 0));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BUS DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel1)
                .addContainerGap(478, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("FILTER BY :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("AVAILABILITY:");

        buttonGroup1.add(availyes);
        availyes.setForeground(new java.awt.Color(51, 51, 51));
        availyes.setText("YES");
        availyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availyesActionPerformed(evt);
            }
        });

        buttonGroup1.add(availno);
        availno.setForeground(new java.awt.Color(51, 51, 51));
        availno.setText("NO");
        availno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availnoActionPerformed(evt);
            }
        });

        BusTable.setBackground(new java.awt.Color(204, 204, 204));
        BusTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BusTable.setForeground(new java.awt.Color(102, 102, 102));
        BusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "BUS ID", "BUS NUMBER", "CAPACITY", "AVAILABILITY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        BusTable.setGridColor(new java.awt.Color(153, 153, 153));
        BusTable.setRowHeight(25);
        BusTable.setSelectionBackground(new java.awt.Color(102, 153, 255));
        jScrollPane1.setViewportView(BusTable);

        show_bus.setBackground(new java.awt.Color(102, 153, 255));
        show_bus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        show_bus.setForeground(new java.awt.Color(255, 255, 255));
        show_bus.setText("SHOW");
        show_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_busActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(availyes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(availno)
                .addGap(69, 69, 69)
                .addComponent(show_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availyes)
                    .addComponent(availno)
                    .addComponent(show_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void availyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availyesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availyesActionPerformed

    private void availnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availnoActionPerformed

    private void show_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_busActionPerformed
    int AVAIL = -1;
    if (availyes.isSelected()) {
        AVAIL = 1;
    } else if (availno.isSelected()) {
        AVAIL = 0;
    }

    // Construct the base SQL query without any filters.
    StringBuilder sql = new StringBuilder("SELECT * FROM BUS");

    // Create a list to store filter conditions.
    ArrayList<String> conditions = new ArrayList<>();
    if (AVAIL != -1) {
        conditions.add("AVAILABILITY = ?");
    }
    // Append the filter conditions with 'AND' in the SQL query if any filters are selected.
    if (!conditions.isEmpty()) {
        sql.append(" WHERE ").append(String.join(" AND ", conditions));
    }

    try {
        PreparedStatement pst = con.prepareStatement(sql.toString());

        int parameterIndex = 1;
        if (AVAIL != -1) {
            pst.setInt(parameterIndex++, AVAIL);
        }

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) BusTable.getModel();
        model.setRowCount(0); // Clear the existing table rows.

        while (rs.next()) {
            // Retrieve data from the ResultSet and add it to the table model.
            model.addRow(new String[]{
                rs.getString(1),
                rs.getString(2), 
                rs.getString(3), 
                rs.getString(4)
            });
        }

        pst.close(); // Close the PreparedStatement.

    } catch (SQLException ex) {
        // Handle any database-related errors.
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_show_busActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BusTable;
    private javax.swing.JRadioButton availno;
    private javax.swing.JRadioButton availyes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton show_bus;
    // End of variables declaration//GEN-END:variables
}
