/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bip;

import java.awt.Color;
import java.awt.Font;
import java.awt.List;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesus
 */
public class viewstudent extends javax.swing.JInternalFrame {

    /**
     * Creates new form student
     */
    Connection con;
    DBConnect dbc= new DBConnect();
    public viewstudent() {
        initComponents();
        try {
            con=dbc.Connect();
        } catch (SQLException ex) {
            Logger.getLogger(LOGIN.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        honors = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        dept = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        availyes = new javax.swing.JRadioButton();
        availno = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        show_student = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 0));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" STUDENT DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel1)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        honors.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        honors.setForeground(new java.awt.Color(102, 102, 102));
        honors.setText("HONORS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("FILTER BY :");

        dept.setForeground(new java.awt.Color(102, 102, 102));
        dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Nil-", "CSE", "IT", "EEE", "ECE", "MECH", "CIVIL", "BME", "AIDS", "BT" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("DEPT:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("YEAR:");

        year.setForeground(new java.awt.Color(51, 51, 51));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Nil-", "I", "II", "III", "IV" }));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("AVAILABILITY:");

        buttonGroup1.add(availyes);
        availyes.setForeground(new java.awt.Color(51, 51, 51));
        availyes.setText("YES");
        availyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availyesActionPerformed(evt);
            }
        });

        buttonGroup1.add(availno);
        availno.setForeground(new java.awt.Color(51, 51, 51));
        availno.setText("NO");
        availno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availnoActionPerformed(evt);
            }
        });

        StudentTable.setBackground(new java.awt.Color(204, 204, 204));
        StudentTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StudentTable.setForeground(new java.awt.Color(102, 102, 102));
        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ADMIN NO", "NAME", "DEPARTMENT", "YEAR", "DESTINATION", "TRIP2", "AVAILABLE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        StudentTable.setGridColor(new java.awt.Color(153, 153, 153));
        StudentTable.setRowHeight(25);
        StudentTable.setSelectionBackground(new java.awt.Color(102, 153, 255));
        jScrollPane1.setViewportView(StudentTable);

        show_student.setBackground(new java.awt.Color(102, 153, 255));
        show_student.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        show_student.setForeground(new java.awt.Color(255, 255, 255));
        show_student.setText("SHOW");
        show_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_studentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58)
                        .addComponent(honors)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(availyes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(availno)
                        .addGap(27, 27, 27)
                        .addComponent(show_student, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(honors)
                            .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(availyes)
                            .addComponent(availno)
                            .addComponent(show_student, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void availyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availyesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availyesActionPerformed

    private void availnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availnoActionPerformed

    private void show_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_studentActionPerformed
    String DEPT = dept.getSelectedItem().toString();
    String YEAR = year.getSelectedItem().toString();
    String HONORS = null;
    int AVAIL = -1;
    if (honors.isSelected()) {
        HONORS = "YES";
    }
    if (availyes.isSelected()) {
        AVAIL = 1;
    } else if (availno.isSelected()) {
        AVAIL = 0;
    }
    StringBuilder sql = new StringBuilder("SELECT * FROM STUDENT");
    // Create a list to store filter conditions.
    ArrayList<String> conditions = new ArrayList<>();
    if (HONORS != null) {
        conditions.add("TRIP2 = ?");
    }
    if (!"-Nil-".equals(DEPT)) {
        conditions.add("DEPARTMENT = ?");
    }
    if (!"-Nil-".equals(YEAR)) 
    {
        conditions.add("YEAR = ?");
    }
    if (AVAIL != -1) {
        conditions.add("AVAILABLE = ?");
    }
    if (!conditions.isEmpty()) {
        sql.append(" WHERE ").append(String.join(" AND ", conditions));
    }
    try {
        PreparedStatement pst = con.prepareStatement(sql.toString());
        int parameterIndex = 1;
        if (HONORS != null) {
            pst.setString(parameterIndex++, HONORS);
        }
        if (!"-Nil-".equals(DEPT)) {
            pst.setString(parameterIndex++, DEPT);
        }
        if (!"-Nil-".equals(YEAR)) {
            pst.setString(parameterIndex++, YEAR);
        }
        if (AVAIL != -1) {
            pst.setInt(parameterIndex++, AVAIL);
        }
        ResultSet rs = pst.executeQuery();
        DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
        model.setRowCount(0); 
        while (rs.next()) {
            model.addRow(new String[]{
                rs.getString(1),
                rs.getString(2), 
                rs.getString(3),
                rs.getString(4), 
                rs.getString(5), 
                rs.getString(6),
                rs.getString(7)  
            });
        }
        pst.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_show_studentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StudentTable;
    private javax.swing.JRadioButton availno;
    private javax.swing.JRadioButton availyes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dept;
    private javax.swing.JRadioButton honors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton show_student;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
